import Image from 'next/image'

import { Container } from '@/components/Container'
import backgroundImage from '@/images/background-faqs.jpg'

const faqs = [
  [
    {
      question: 'How does Intelliscan detect if code is AI-generated or human-written?',
      answer:
        'Intelliscan uses advanced AI models to analyze the structure and patterns of code, identifying whether it was generated by AI or written by a human developer.',
    },
    {
      question: 'Can Intelliscan detect plagiarism in any code file format?',
      answer:
        'Yes, Intelliscan supports all code file types and performs a thorough, word-by-word comparison to detect any unauthorized similarities between code files.',
    },
    {
      question: 'Does Intelliscan support plagiarism detection for large projects?',
      answer:
        'Absolutely! Intelliscan is designed to handle code from both small and large projects, ensuring accurate plagiarism detection across the entire codebase.',
    },
  ],
  [
    {
      question: 'What is RAG-based chatbot assistance in Intelliscan?',
      answer:
        'The RAG-based chatbot provides users with instant, personalized answers related to their coding problems and guidance on how to use the platform effectively.',
    },
    {
      question: 'How does Intelliscan help students with learning resources?',
      answer:
        'Intelliscan serves as an all-in-one learning hub, gathering top learning resources from the web, GitHub, and YouTube using an intelligent, RESTful API-based system.',
    },
    {
      question: 'Is the plagiarism detection in Intelliscan fast and accurate?',
      answer:
        'Yes, Intelliscan uses cutting-edge machine learning models to quickly analyze and detect plagiarism with high accuracy, even across large codebases.',
    },
  ],
  [
    {
      question: 'How does Intelliscan ensure the integrity of my code?',
      answer:
        'Intelliscan provides fast, accurate plagiarism detection to ensure your code remains original and free from unauthorized similarities. It protects your project’s integrity with ease.',
    },
    {
      question: 'What kind of reports does Intelliscan generate after plagiarism detection?',
      answer:
        'Intelliscan generates detailed reports that highlight matching sections, provide similarity scores, and offer a comprehensive view of potential plagiarism risks.',
    },
    {
      question: 'Is Intelliscan suitable for both professional and academic use?',
      answer:
        'Yes, Intelliscan is designed to meet the needs of both professionals and students, offering robust features to detect code plagiarism and ensure originality across multiple programming languages.',
    },
  ],
];


export function Faqs() {
  return (
    <section
      id="faq"
      aria-labelledby="faq-title"
      className="relative overflow-hidden bg-slate-50 py-20 sm:py-32"
    >
      <Image
        className="absolute left-1/2 top-0 max-w-none -translate-y-1/4 translate-x-[-30%]"
        src={backgroundImage}
        alt=""
        width={1558}
        height={946}
        unoptimized
      />
      <Container className="relative">
        <div className="mx-auto max-w-2xl lg:mx-0">
          <h2
            id="faq-title"
            className="font-display text-3xl tracking-tight text-slate-900 sm:text-4xl"
          >
            Frequently asked questions
          </h2>
          <p className="mt-4 text-lg tracking-tight text-slate-700">
            {/* If you can’t find what you’re looking for, email our support team
            and if you’re lucky someone will get back to you. */}
          </p>
        </div>
        <ul
          role="list"
          className="mx-auto mt-16 grid max-w-2xl grid-cols-1 gap-8 lg:max-w-none lg:grid-cols-3"
        >
          {faqs.map((column, columnIndex) => (
            <li key={columnIndex}>
              <ul role="list" className="flex flex-col gap-y-8">
                {column.map((faq, faqIndex) => (
                  <li key={faqIndex}>
                    <h3 className="font-display text-lg leading-7 text-slate-900">
                      {faq.question}
                    </h3>
                    <p className="mt-4 text-sm text-slate-700">{faq.answer}</p>
                  </li>
                ))}
              </ul>
            </li>
          ))}
        </ul>
      </Container>
    </section>
  )
}
